#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('commander');
var logger = require('./bin/logging.js');
var fs = require('fs');
var path = require('path');
var settings = require('./settings.json');

function list(val) {
  return val.split(',').map(Number);
}

program
  .version('0.0.1a')
  .option('-c, --create', 'Create a new Nirodha project')
  .option('-s, --start', 'Start hosting the Nirodha project, to enable compression pass withCompression to the -s switch')
  .option('-d, --deploy', 'Compile the Nirodha project to the deploy folder');

// must be before .parse() since
// node's emit() is immediate

program.on('--help', function(){
  console.log('  Examples:');
  console.log('');
  console.log('    $ custom-help --help');
  console.log('    $ custom-help -h');
  console.log('');
});

program.parse(process.argv);

/*  Nirodha Source Code
 *  Author: Brent Jameson
 *  Date: Oct 24 2013
 */

// Temp hack to not accept two arguments
var argumentCount = 0;

// Try to get the settings from the nirodha config file in current directory
var currentSettings;
logger.log('Try to get the settings from info.json...');
try {
  currentSettings = require(process.cwd() + '/info.json');
  logger.log('Settings set: ' + JSON.stringify(currentSettings));
}
catch(err) {
  logger.log('Error occured getting the settings, most likely they do not exists: ' + err);
  currentSettings = null;
}

var defaultSettings = require('./tmpl/newproject.default.json');
var inNirodaWorkingDir = false;

logger.log('Current directory: ' + process.cwd());

// Check the settings of the file and determine if we are compatible
if(currentSettings) {
  logger.log('In a Nirodha working directory')
  if(currentSettings.version === defaultSettings.version) {
    logger.log('In a compatible version for the Nirodha working directory');
    inNirodaWorkingDir = true;
  }
  else {
    console.log('The version of this Nirodha project is not compatible with the running version of Nirodha...');
  }
}

if(program.create) {
  argumentCount++;
}

if(program.start) {
  argumentCount++;
}

if(program.deploy) {
  argumentCount++;
}

if(argumentCount != 1) {
  console.log("An incorrect number of arguments was specified: " + argumentCount);
  if(argumentCount == 0) {
    console.log("There were no arguments processed, perhaps you are missing a switch like '-c'? Consult 'nirodha -h' for more info");
  }
  else {
    console.log("Too many arguments...");
  }
}
else {
  if(program.create) {
    var create = require('./bin/create.js');
    if(inNirodaWorkingDir) {
      logger.log('Trying to run create inside of a nirodha project', 0);
      if(program.args[0] === 'view' && program.args.length == 2) {
        logger.log('Creating view for ' + program.args[1]);
        create(program.args);
      }
      else {
        logger.log('Received an unknown command');
      }
    }
    else {
      create(program.args);
    }
  }

  if(program.start) {
    if(inNirodaWorkingDir) {
      var start = require('./bin/start.js');
      start(program.args);
    }
    else {
      console.log('Not a valid Nirodha project');
    }
  }

  if(program.deploy) {
    var deploy = require('./bin/deploy.js');
    deploy(program.args);
  }
}